local cmd = vim.cmd

cmd [[ syntax on ]]
cmd [[ set t_Co=256 ]]
cmd [[ set laststatus=2 ]]
cmd [[ filetype plugin indent on ]]
cmd [[ set number ]]
cmd [[ set tabstop=4 ]]
cmd [[ set shiftwidth=4 ]]
cmd [[ set expandtab ]]
cmd [[ set noshowmode ]]
cmd [[ set encoding=utf-8 ]]
cmd [[ set relativenumber ]]
cmd [[ set cursorline ]]
cmd [[ set smarttab ]]
-- cmd [[ "set listchars=tab:>·,extends:>,precedes:<,space:. ]]
-- cmd [[ "set list ]]
cmd [[ nmap <C-a> :NvimTreeToggle<CR> ]]
cmd [[ map <C-h> <C-w>h ]]
cmd [[ map <C-j> <C-w>j ]]
cmd [[ map <C-k> <C-w>k ]]
cmd [[ map <C-l> <C-w>l ]]
cmd [[ nmap te :tabe<CR> ]]
cmd [[ nmap tr :bn<CR> ]]
cmd [[ nmap ty :bp<CR> ]]
cmd [[ nmap td :bd<CR> ]]
cmd [[ nmap th :split<CR> ]]
cmd [[ nmap tv :vsplit<CR> ]]
